#include "keycodes.h"
#include QMK_KEYBOARD_H
// #include "keymap_neo2.h"
#include "keymap_german.h"
#include "action_layer.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Unicode input
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
#define UNICODE_KEY_LNX LCTL(LSFT(DE_U))

// Configuration for tap_hold
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPING_TERM 200

// bitmasks for modifier keys
#define MODS_NONE   0
#define MODS_SHIFT  (MOD_BIT(KC_LSFT)|MOD_BIT(KC_RSFT))
#define MODS_CTRL   (MOD_BIT(KC_LCTL)|MOD_BIT(KC_RCTL))
#define MODS_ALT    (MOD_BIT(KC_LALT)|MOD_BIT(KC_RALT))
#define MODS_GUI    (MOD_BIT(KC_LGUI)|MOD_BIT(KC_RGUI))

enum custom_keycodes {
    PLACEHOLDER = SAFE_RANGE,     // can always be here
    NMOD3,
    NEO2_RMOD3,
    NEO2_1,
    NEO2_2,
    NEO2_3,
    NEO2_4,
    NEO2_5,
    NEO2_6,
    NEO2_7,
    NEO2_8,
    NEO2_9,
    NEO2_0,
    NEO2_MINUS,
    NEO2_COMMA,
    NEO2_DOT,
    NEO2_SHARP_S,
};

// NEO_3 special characters
#define N3_CAPITAL_SS           RSA(DE_S)                   // ẞ
#define N3_CAPITAL_UE           S(DE_UDIA)                  // Ü
#define N3_CAPITAL_OE           S(DE_ODIA)                  // Ö
#define N3_CAPITAL_AE           S(DE_ADIA)                  // Ä
#define N3_SUP1                 RALT(DE_1)                  // ¹
#define N3_SUP2                 DE_SUP2                     // ²
#define N3_SUP3                 DE_SUP3                     // ³
#define N3_RSAQUO               RSA(DE_Y)                   // ›
#define N3_LSAQUO               RSA(DE_X)                   // ‹
#define N3_RAQUO                RALT(DE_Y)                  // »
#define N3_LAQUO                RALT(DE_X)                  // «
#define N3_CENT                 RALT(DE_C)                  // ¢
#define N3_YEN                  RSA(DE_Z)                   // ¥
#define N3_SBQUO                RSA(DE_V)                   // ‚
#define N3_LSQ                  RSA(DE_B)                   // ‘
#define N3_RSQ                  RSA(DE_N)                   // ’
#define N3_LOW9_DBQUOTE         RALT(DE_V)                  // „
#define N3_LEFT_DBQUOTE         RALT(DE_B)                  // “
#define N3_RIGHT_DBQUOTE        RALT(DE_N)                  // ”
#define N3_ELLIPSIS             RALT(DE_DOT)                // …
#define N3_UNDRSCR              DE_UNDS                     // _
#define N3_LBRACKET             DE_LBRC                     // [
#define N3_RBRACKET             DE_RBRC                     // ]
#define N3_CIRCUMFLEX           DE_CIRC                     // ^
#define N3_EXCLAMATION          DE_EXLM                     // !
#define N3_LESSTHAN             DE_LABK                     // <
#define N3_GREATERTHAN          DE_RABK                     // >
#define N3_EQUAL                DE_EQL                      // =
#define N3_AMPERSAND            DE_AMPR                     // &
#define N3_SMALL_LONG_S         RALT(DE_S)                  // ſ
#define N3_BSLASH               DE_BSLS                     // (backslash)
#define N3_SLASH                DE_SLSH                     // /
#define N3_CLBRACKET            DE_LCBR                     // {
#define N3_CRBRACKET            DE_RCBR                     // }
#define N3_ASTERISK             DE_ASTR                     // *
#define N3_QUESTIONMARK         DE_QUES                     // ?
#define N3_LPARENTHESES         DE_LPRN                     // (
#define N3_RPARENTHESES         DE_RPRN                     // )
#define N3_HYPHEN_MINUS         DE_MINS                     // -
#define N3_COLON                DE_COLN                     // :
#define N3_AT                   DE_AT                       // @
#define N3_HASH                 DE_HASH                     // #
#define N3_PIPE                 DE_PIPE                     // |
#define N3_TILDE                DE_TILD                     // ~
#define N3_BACKTICK             DE_GRV                      // `
#define N3_PLUS                 DE_PLUS                     // +
#define N3_PERCENT              DE_PERC                     // %
#define N3_DOUBLE_QUOTE         DE_DQUO                     // "
#define N3_SINGLE_QUOTE         DE_QUOT                     // '
#define N3_SEMICOLON            DE_SCLN                     // ;

// NEO_4 special characters
#define N4_FEMININE_ORDINAL     RSA(DE_F)                   // ª
#define N4_MASCULINE_ORDINAL    RSA(DE_M)                   // º
#define N4_NUMERO_SIGN          KC_NO                       // №
#define N4_MIDDLE_DOT           RALT(DE_COMM)               // ·
#define N4_BRITISH_POUND        RSA(DE_3)                   // £
#define N4_CURRENCY_SIGN        RSA(DE_4)                   // ¤
#define N4_INVEX                RSA(DE_1)                   // ¡
#define N4_INVQS                RSA(DE_SS)                  // ¿
#define N4_DOLLAR               DE_DLR                      // $
#define N4_EN_DASH              RALT(DE_MINS)               // –
#define N4_EM_DASH              RSA(DE_MINS)                // —
//
enum unicode_names {
    G_ALPHA,
    S_n,
    S_N,
    SCRIPT_L,  // Add this
};

const uint32_t PROGMEM unicode_map[] = {
    [G_ALPHA] = 0x03B1, // Unicode for α (Greek Alpha)
    [S_n] = 0x00F1, // Unicode for α
    [S_N] = 0x00D1, // Unicode for α
    [SCRIPT_L] = 0x2113,  // Unicode for ℓ
    // Assign more Unicode characters as needed
};

// State bitmap to track which key(s) enabled NEO_3 layer
static uint8_t neo3_state = 0;
// State bitmap to track key combo for CAPSLOCK
static uint8_t capslock_state = 0;

#define KC_MLSFT LM(_NOTED_SHIFT, KC_LSFT)
#define KC_MRSFT LM(_NOTED_SHIFT, KC_RSFT)
#define CTL_SPC LCTL_T(KC_SPC)
#define CTL_ENT LCTL_T(KC_ENT)
#define SWAY_CMB LGUI(KC_LSFT)

// Define layers
enum layer_number {
    _NOTED = 0,
    _NEO_3,
    _NEO_4,
    _NEO_5,
    _NEO_6,
    _FN_KEYS,
    _QWRTY,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
// *INDENT-OFF*
/* Noted
 * Small difference with the normal NEO is that I am using the function keys instead of the numbers on the
 * upper most row.
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |  ^/° | F1/° | F2/§ | F3/  | F4/» | F5/« |                    | F6/$ | F7/€ | F8/„ | F9/“ | F10/”|  -/— |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |  J   |   Z  |   Y  |   U  |   A  |   Q  |                    |   P  |   B  |   M  |   L  |   F  |  ß   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | Neo3 |   C  |   S  |   I  |   E  |   O  |-------.    ,-------|   D  |   T  |   N  |   R  |   H  | Neo3 |
 * |------+------+------+------+------+------|  Del  |    | BckSP |------+------+------+------+------+------|
 * |LShift|   V  |   X  |   Ü  |   Ä  |   Ö  |-------|    |-------|   W  |   G  |   ,  |   .  |   K  |RShift|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   | lalt | LGUI | Neo4 | /Space  /       \Enter \  | Neo4 | GUI+ | MEDIA|
 *                   |      |      |      |/ (CTRL)/         \(CTRL)\ |      | Shift|      |
 *                   `----------------------------'           '------''--------------------'
 */

 [_NOTED] = LAYOUT(
  DE_CIRC,    NEO2_1, NEO2_2,  NEO2_3,  NEO2_4,  NEO2_5,                  NEO2_6,  NEO2_7,  NEO2_8,  NEO2_9,  NEO2_0, NEO2_MINUS,
  DE_J,       DE_Z,     DE_Y,    DE_U,    DE_A,    DE_Q,                    DE_P,    DE_B,    DE_M,    DE_L,    DE_F,      DE_SS,
  NMOD3,      DE_C,     DE_S,    DE_I,    DE_E,    DE_O,                    DE_D,    DE_T,    DE_N,    DE_R,    DE_H,      NMOD3,
  KC_LSFT,    DE_V,     DE_X, DE_UDIA, DE_ADIA, DE_ODIA, KC_DEL,   KC_BSPC, DE_W,    DE_G, DE_COMM,  DE_DOT,    DE_K,    KC_RSFT,
                           KC_LALT, KC_LGUI, MO(_NEO_4), CTL_SPC,  CTL_ENT, MO(_NEO_4), SWAY_CMB, MO(_FN_KEYS)
),
/* NEO 3
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |  ¹   |  ²   |   ³  |   ›  |   ‹  |                    |   ¢  |   ¥  |   ‚  |   ‘  |   ’  |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   …  |   _  |   [  |   ]  |   ^  |                    |   !  |   <  |   >  |   =  |   &  |   @  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   \  |   /  |   {  |   }  |   *  |-------.    ,-------|   ?  |   (  |   )  |   -  |   :  |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |      |   #  |   $  |   |  |   ~  |   `  |-------|    |-------|   +  |   %  |   "  |   '  |   ;  |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \      \  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
[_NEO_3] = LAYOUT(
  _______,     N3_SUP1,    DE_SUP2, DE_SUP3, N3_RSAQUO, N3_LSAQUO,                     N3_CENT,  N3_YEN, N3_SBQUO,  N3_LSQ,  N3_RSQ, _______,
  _______, N3_ELLIPSIS, N3_UNDRSCR, DE_LBRC,   DE_RBRC,   DE_CIRC,                     DE_EXLM, DE_LABK,  DE_RABK,  DE_EQL, DE_AMPR,   DE_AT,
  _______,   N3_BSLASH,   N3_SLASH, DE_LCBR,   DE_RCBR,   DE_ASTR,                     DE_QUES, DE_LPRN,  DE_RPRN, DE_MINS, DE_COLN, _______,
  _______,     DE_HASH,     DE_DLR, DE_PIPE,   DE_TILD,    DE_GRV,  KC_INS,   UP(S_n, S_N), DE_PLUS, DE_PERC,  DE_DQUO, DE_QUOT, DE_SCLN, _______,
                                        _______, _______, _______, _______,   _______, _______, _______, _______
),
/* NEO 4 (or something similar)
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  |  F10 |  F11 |  F12 |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | Tab  |  7   |  8   |  9   |  +   |                    |   ¡  |      | End  | Home |   ´  | PrScr|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | Esc  |  4   |  5   |  6   |  .   |-------.    ,-------|   ¿  | Left | Down |  Up  | Right|      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |      |      |  1   |  2   |  3   |  ,   |-------|    |-------|      |      |      |      |      |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /  0    /       \ Enter\  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */

[_NEO_4] = LAYOUT(
  XXXXXXX,  KC_F11, KC_F12, KC_F13, KC_F14,  KC_F15,                        KC_F16,  KC_F17,  KC_F18,  KC_F19,   KC_F20, XXXXXXX,
  XXXXXXX,  KC_TAB,   KC_7,   KC_8,   KC_9, DE_PLUS,                      N4_INVEX, XXXXXXX,  KC_END, KC_HOME,  DE_ACUT, KC_PSCR,
  _______,  KC_ESC,   KC_4,   KC_5,   KC_6,  DE_DOT,                      N4_INVQS, KC_LEFT, KC_DOWN,   KC_UP, KC_RIGHT, _______,
  _______, XXXXXXX,   KC_1,   KC_2,   KC_3, DE_COMM, _______, DF(_QWRTY),  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, _______,
                          _______, _______, _______,    KC_0,     KC_ENT,  _______, _______, _______
),
/* Media keys
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------.    ,-------|      |      |      |      |      |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------|    |-------|      |      |      |      |      |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \      \  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */

[_FN_KEYS] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, KC_MUTE, KC_VOLD, KC_VOLU, KC_BRIU,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, KC_BRID,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                             XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______
),
/* QWERTY
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------.    ,-------|      |      |      |      |      |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------|    |-------|      |      |      |      |      |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \      \  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
[_QWRTY] = LAYOUT(
   KC_ESC,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_GRV,
   KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                      KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_MINS,
  KC_LCTL,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                      KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, KC_QUOT,
  KC_LSFT,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B, KC_LBRC, KC_RBRC,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_RSFT,
                             KC_LALT, KC_LGUI, KC_LALT,  KC_SPC,  KC_ENT,   DF(_NOTED), KC_BSPC, KC_RGUI
),
};

// *INDENT-ON*
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

// Send a key tap with a optional set of modifiers.
void tap_with_modifiers(uint16_t keycode, uint8_t force_modifiers) {
    uint8_t active_modifiers = get_mods();

    // Clear all mods temporarily
    clear_mods();

    // Apply forced modifiers
    if (force_modifiers & MODS_SHIFT) register_code(KC_LSFT);
    if (force_modifiers & MODS_CTRL) register_code(KC_LCTL);
    if (force_modifiers & MODS_ALT) register_code(KC_RALT);  // Changed from KC_LALT to KC_RALT
    if (force_modifiers & MODS_GUI) register_code(KC_LGUI);

    // Small delay to ensure modifiers are registered
    wait_ms(10);

    // Send the keycode
    register_code(keycode);
    wait_ms(10);  // Small delay before release
    unregister_code(keycode);

    // Remove forced modifiers
    if (force_modifiers & MODS_SHIFT) unregister_code(KC_LSFT);
    if (force_modifiers & MODS_CTRL) unregister_code(KC_LCTL);
    if (force_modifiers & MODS_ALT) unregister_code(KC_RALT);  // Changed from KC_LALT to KC_RALT
    if (force_modifiers & MODS_GUI) unregister_code(KC_LGUI);

    // Restore original modifiers
    set_mods(active_modifiers);
}

// Special remapping for keys with different keycodes/macros when used with shift modifiers.
bool process_record_user_shifted(uint16_t keycode, keyrecord_t *record) {
    uint8_t active_modifiers = get_mods();
    uint8_t shifted = active_modifiers & MODS_SHIFT;

    // Early return on key release
    if(!record->event.pressed) {
        return true;
    }

    if(shifted) {
        clear_mods();

        switch(keycode) {
        case NEO2_1:
            // degree symbol
            tap_with_modifiers(KC_GRV, MODS_SHIFT);
            break;
        case NEO2_2:
            // section symbol
            tap_with_modifiers(KC_3, MODS_SHIFT);
            break;
        case NEO2_3:
            // ℓ
            register_unicode(0x2113);
            break;
        case NEO2_4:
            // right angled quote
            tap_with_modifiers(KC_Z, MODS_ALT);
            break;
        case NEO2_5:
            // left angled quote
            tap_with_modifiers(KC_X, MODS_ALT);
            break;
        case NEO2_6:
            // dollar sign
            tap_with_modifiers(KC_4, MODS_SHIFT);
            break;
        case NEO2_7:
            // euro sign
            tap_with_modifiers(KC_E, MODS_ALT);
            break;
        case NEO2_8:
            // low9 double quote
            tap_with_modifiers(KC_V, MODS_ALT);
            break;
        case NEO2_9:
            // left double quote
            tap_with_modifiers(KC_B, MODS_ALT);
            break;
        case NEO2_0:
            // right double quote
            tap_with_modifiers(KC_N, MODS_ALT);
            break;
        case NEO2_MINUS:
            // em dash
            tap_with_modifiers(KC_SLSH, MODS_SHIFT | MODS_ALT);
            break;
        case NEO2_COMMA:
            // en dash
            tap_with_modifiers(KC_SLSH, MODS_ALT);
            break;
        case NEO2_DOT:
            // bullet
            tap_with_modifiers(KC_COMM, MODS_ALT);
            break;
        case NEO2_SHARP_S:
            // ẞ
            tap_with_modifiers(KC_S, MODS_SHIFT | MODS_ALT);
            break;
        default:
            set_mods(active_modifiers);
            return true;
        }

        set_mods(active_modifiers);
        return false;
    } else {
        switch(keycode) {
        case NEO2_1:
            tap_with_modifiers(KC_F1, MODS_NONE);
            break;
        case NEO2_2:
            tap_with_modifiers(KC_F2, MODS_NONE);
            break;
        case NEO2_3:
            tap_with_modifiers(KC_F3, MODS_NONE);
            break;
        case NEO2_4:
            tap_with_modifiers(KC_F4, MODS_NONE);
            break;
        case NEO2_5:
            tap_with_modifiers(KC_F5, MODS_NONE);
            break;
        case NEO2_6:
            tap_with_modifiers(KC_F6, MODS_NONE);
            break;
        case NEO2_7:
            tap_with_modifiers(KC_F7, MODS_NONE);
            break;
        case NEO2_8:
            tap_with_modifiers(KC_F8, MODS_NONE);
            break;
        case NEO2_9:
            tap_with_modifiers(KC_F9, MODS_NONE);
            break;
        case NEO2_0:
            tap_with_modifiers(KC_F10, MODS_NONE);
            break;
        case NEO2_MINUS:
            tap_with_modifiers(KC_SLSH, MODS_NONE);
            break;
        case NEO2_COMMA:
            tap_with_modifiers(KC_COMM, MODS_NONE);
            break;
        case NEO2_DOT:
            tap_with_modifiers(KC_DOT, MODS_NONE);
            break;
        case NEO2_SHARP_S:
            tap_with_modifiers(KC_MINS, MODS_NONE);
            break;
        case N3_CIRCUMFLEX:
            tap_with_modifiers(KC_GRV, MODS_NONE);
            tap_with_modifiers(KC_SPC, MODS_NONE);
            break;
        case N3_BACKTICK:
            tap_with_modifiers(KC_EQL, MODS_SHIFT);
            tap_with_modifiers(KC_SPC, MODS_NONE);
            break;
        default:
            return true;
        }

        return false;
    }

}

// Runs for each key down or up event.
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch(keycode) {
    case KC_LSFT:
        if (record->event.pressed) {
            capslock_state |= (MOD_BIT(KC_LSFT));
        } else {
            capslock_state &= ~(MOD_BIT(KC_LSFT));
        }
        break;
    case KC_RSFT:
        if (record->event.pressed) {
            capslock_state |= MOD_BIT(KC_RSFT);
        } else {
            capslock_state &= ~(MOD_BIT(KC_RSFT));
        }
        break;
    case NMOD3:
        if (record->event.pressed) {
            layer_on(_NEO_3);
            neo3_state |= (1 << 1);
        } else {
            // Turn off _NEO_3 layer unless it's enabled through NEO2_RMOD3 as well.
            if ((neo3_state & ~(1 << 1)) == 0) {
                layer_off(_NEO_3);
            }
            neo3_state &= ~(1 << 1);
        }
        break;
    }

    return process_record_user_shifted(keycode, record);
};


// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {

};

bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
    // Keycodes that continue Caps Word, with shift applied.
    case DE_A:
    case DE_B:
    case DE_C:
    case DE_D:
    case DE_E:
    case DE_F:
    case DE_G:
    case DE_H:
    case DE_I:
    case DE_J:
    case DE_K:
    case DE_L:
    case DE_M:
    case DE_N:
    case DE_O:
    case DE_P:
    case DE_Q:
    case DE_R:
    case DE_S:
    case DE_T:
    case DE_U:
    case DE_V:
    case DE_W:
    case DE_X:
    case DE_Y:
    case DE_Z:
    case DE_ODIA:
    case DE_UDIA:
    case DE_ADIA:
    case N3_UNDRSCR:
    case KC_MINS:
        add_weak_mods(MOD_BIT(KC_LSFT));  // Apply shift to next key.
        return true;

    // Keycodes that continue Caps Word, without shifting.
    case KC_1 ... KC_0:
    case KC_BSPC:
    case NEO2_RMOD3:
    case NMOD3:
    case KC_DEL:
    case KC_UNDS:
        return true;

    default:
        return false;  // Deactivate Caps Word.
    }
}
